### ISSUE TITLE
vue 2?

### ISSUE THREAD

**Issue by fabioselau077** [bahadirsofuoglu/form-wizard-vue3#12]
Hello, thanks for component, very good.

But one question: How to use in Vue 2? Or have alternative this component for Vue 2?

Thanks

**Comment by bahadirsofuoglu** [comment]
Hi Fabio,
Thank you for your kind comment. made me very happy. You know vue official version is 3. So I wrote for only vue3. But I planned to write for Vue2. Added my backlog. If you need a form wizard library you can check this. Very popular library for Vue2. https://binarcode.github.io/vue-form-wizard/#/

**Comment by mrengineer19** [comment]
Any update on vue2?
