### ISSUE TITLE
How to add action on Done?

### ISSUE THREAD

**Issue by jesehl** [bahadirsofuoglu/form-wizard-vue3#13]
How to put function on done?

**Comment by bahadirsofuoglu** [comment]
Hi,
You can use complete:wizard emit.

**Comment by paulohfsantos** [comment]
Hello!

Is there any event for next and back buttons?

**Comment by jesehl** [comment]
Not sure how to use. Kindly put a sample code. Done button is not clickable.. 

Wizard looks good btw.

**Comment by paulohfsantos** [comment]
> Not sure how to use. Kindly put a sample code. Done button is not clickable..
> 
> Wizard looks good btw.

@complete:wizard="onDone"

methods: {
   onDone() { console.log('done') }
}

**Comment by bahadirsofuoglu** [comment]
Hi @jesehl,
Thank you for your kind comment. I added an example to the live demo.

**Comment by jesehl** [comment]
@bahadirsofuoglu made it work! thanks.
