### ISSUE TITLE
I can't modify the styles

### ISSUE THREAD

**Issue by YulianaTrifonova** [bahadirsofuoglu/form-wizard-vue3#16]
Hi! I'm trying to use the form wizard, but I'm facing trouble modifying the styles. For example, I want to change the border color of the tabs (.form-wizard-vue .fw-step-checked) but even with !important, the browser doesn't read them. The funny thing is that when i tried my code in the live demo it worked as a charm. Can you tell me how can i fix that?

**Comment by bahadirsofuoglu** [comment]
Hi, 
I think u should use ':deep' for accessing child components class. 
https://vuejs.org/api/sfc-css-features.html#scoped-css
