### ISSUE TITLE
Prevent change on invalid state

### ISSUE THREAD

**Issue by capoia** [bahadirsofuoglu/form-wizard-vue3#18]
Hello, first I wanted to thank you for the component, it's getting very good!

I'm using vuelidate to validate my steps form, I'm trying in the change event not to let it go to the next step if it's invalid, in fact the form doesn't leave the first step, but the steps keep changing anyway.

![image](https://user-images.githubusercontent.com/21159928/187458046-80702442-0ac7-461f-bbc5-2cab0d6508f6.png)

As you can see in the video.

https://user-images.githubusercontent.com/21159928/187457734-df8bbe5d-7920-480f-b2b7-fe7322283ac4.mp4

**Comment by bahadirsofuoglu** [comment]
Thank you for your kind comment. 
I found the problem. After next release, I think you can use the before-change prop for your solution.

**Comment by bclegaspi** [comment]
hi! is this possible now? thanks

**Comment by SciManJD** [comment]
I'm using the latest release and there is no chance to stop changing of the steps. What is the state, is it working now? Can I get a short example, please?

**Comment by hacktolove** [comment]
Hey ! How to stop the step changing?
