### ISSUE TITLE
Possibility of loading or disabling the buttons

### ISSUE THREAD

**Issue by capoia** [bahadirsofuoglu/form-wizard-vue3#19]
Hi, I'm using the component in a project so I'm going to open some issues/feature requests, if it makes sense for the project, I'd be happy to have these features.

The first one is the possibility of disabling the DONE button or putting the wizard in loading mode, because usually at the end of the form an api call is made to save the data...

**Comment by bahadirsofuoglu** [comment]
Thank you very much for your ideas. I definitely want to include it in the project. Right now I spend most of my time on primeVue enhancements, but I'll make improvements as soon as possible. I think loading has a medium, but disable button has high priority.

**Comment by julianatbairesdev** [comment]
Hi, amazing component BTW, I'm currently using this component and would like to suggest the the possibility to no mark as checked the tabs that are not visited, for example, If i go from tab-0 to tab-4, tab-1, 2, 3 are marked as checked even though I haven't even visited them, thanks!
