### ISSUE TITLE
Access to next and previus buttons events

### ISSUE THREAD

**Issue by Koki81** [bahadirsofuoglu/form-wizard-vue3#20]
Hi, I can't use emit change it's not working when I want to change the tab with emit.
trigerNextClick() { let newTabIndex = this.currentTabIndex + 1; let oldTabIndex = this.currentTabIndex; // this.onChangeCurrentTab(newTabIndex, oldTabIndex); this.$emit("change", newTabIndex, oldTabIndex); // this.$refs.wizard; },

**Comment by bahadirsofuoglu** [comment]
Hi, You cant use the change event for tab changing. Change event only for getting current tab index.
