### ISSUE TITLE
change colors

### ISSUE THREAD

**Issue by ludogou** [bahadirsofuoglu/form-wizard-vue3#22]
Hello, when I change the color variables in the "_variables.scss" file, the colors do not change. Is there a solution to change the colors? thank you!

**Comment by bahadirsofuoglu** [comment]
Overriding the variable file will cause problems due to dependency. I will work on it. But for now, you can use this:

`
::v-deep(.form-wizard-vue) {
  .fw-step-active {
    background: black !important;
    color: orange!important;
}
}
`

Thank you very much for the feedback.

**Comment by ludogou** [comment]
Thank you for your reply ! should I put it in my component or in an scss file?

**Comment by bahadirsofuoglu** [comment]
You can add to component style tag.
