### ISSUE TITLE
Slot names and data

### ISSUE THREAD

**Issue by iampapagray** [bahadirsofuoglu/form-wizard-vue3#28]
Hello, thank you for your work on this package.

I'd like to make some customizations on the Vertical Tabs to have a title and subtitle on the right of the icon instead of below it.

From the docs, i should be able to use slots to customize the ui.
Can you point me to the names of the slots available and a sample code on how to implement ?

**Comment by bahadirsofuoglu** [comment]
Hi, I am actively working on templating improvements. Slots will be added to the documents as soon as possible. Thank you very much for your nice comment.
