### ISSUE TITLE
Change the "disabled" option of a button dynamically

### ISSUE THREAD

**Issue by julix14** [bahadirsofuoglu/form-wizard-vue3#31]
Hi, it would be great if you could disable a by default and enable it, when e.g. a specific condition is satisfied. So you could implement a kind of validation.

I tried it in the following way, but it didn't worked:
`:next-button="disableNextButton ? {text: 'Weiter', hideIcon: 'true', disabled: true} : {text: 'Weiter', hideIcon: 'true'}"
`
And here the function that should change the options:
`function disableNextButton() {
    return ((currentTabIndex === 0 && !(selectedPresentation === null)) || (currentTabIndex === 1 && !(selectedFields.length < 2)));
}`

I am pretty new to vue, so if i made a mistake here and the requested feature works already i would be happy getting an explanation of how.

**Comment by bahadirsofuoglu** [comment]
Hi,
I have created an example similar to the situation below. If there is nothing I missed, you can use it like this. If the problem still persists, you can create a reproduce link.
https://stackblitz.com/edit/vue-1bngkw?file=src/App.vue

**Comment by julix14** [comment]
@bahadirsofuoglu Thank you very much. It worked in the way of your example! ❤️

**Comment by emp-sean** [comment]
After doing this is there any way to then unlock the button if a condition has been met?

**Comment by julix14** [comment]
@ubox-sean 
Yes. In my project i solved it in the following way:
In the Wizard-Component i pass a "ref"-Object as Options for the button:
```
<Wizard 
:next-button="nextButton"
```

The object looks like the following:
```
const nextButton = ref({
    text: 'Weiter',
    hideIcon: 'true',
    disabled: true
});
```

When a option in the Wizard is now selected i use the "@click" to validate, if my condition is met or not. If so, i set the disabled attribute of the Object to false and activate the button:
` nextButton.value.disabled = false;
`
